name: v2t
services:
  whisper:
    image: hwdsl2/whisper-server:cuda
    container_name: v2t
    restart: "no"
    volumes:
      - ${HOME}/whisper:/var/lib/whisper
      - ./:/work
    working_dir: /work
    environment:
      WHISPER_MODEL: large-v3
      WHISPER_LANGUAGE: auto
      WHISPER_DEVICE: cuda
      WHISPER_COMPUTE_TYPE: int8_float32
      WHISPER_BEAM: 5
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
